Ewb 508 update network routes to use names instead of id correlator
zepben/ewb-network-routes pull request #25
Opened 2021-02-17 00:46 UTC by var-ram

2021-02-17 00:46 UTC, ryanjcoleman commented
Task linked: [EWB-508 Update network routes to use names instead of id correlator](https://app.clickup.com/t/6929263/EWB-508)

2021-02-17 00:50 UTC, var-ram commented on src/main/java/com/zepben/ewbnetworkroutes/network/translation/TranslatedId.java
> +    public static TranslatedId ofUnmapped(String systemId, String mRID, String systemTag) {
@gcarwardine This is the change I was talking about. The method now takes in a mRID param to cater for the case where the translation from ewb fails because the entity does not have an associated id for the system tag. Initially it was putting the mrid against the systemId which I thought was a bit odd.

2021-02-17 02:02 UTC, charlta commented
@gcarwardine @var-ram Before this is merged you will want to make sure it works in the energy workbench server and ewb network server

2021-02-17 03:06 UTC, charlta requested changes

2021-02-18 03:22 UTC, var-ram commented on src/main/java/com/zepben/ewbnetworkroutes/network/translation/IdTranslator.java
> +        Set<String> translatedIds = new HashSet<>();
Had done this way because `getNames` was returning a sequence and I could not find out a way to convert it into a stream. But I can do it now because Glenn suggested that I change `getNames` to return a list instead of a sequence :)

2021-02-18 05:20 UTC, charlta approved these changes

2021-02-25 03:39 UTC, gcarwardine approved these changes
Good to be merged once all the pieces are ready.

2021-05-10 02:07 UTC, merged